name = "v2raypanel"          # نام دلخواهت (حتماً تغییر بده)
main = "src/worker.ts"
compatibility_date = "2026-05-11"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
